export const STEP_BUTTON_TEXT: string = 'To step';
export const STEP_BUTTON_ICON: string = 'assets/icons/step-icon.png';
export const STEP_BUTTON_ENABLED_ICON: string = 'assets/icons/step-icon.png';
export const STEP_BUTTON_DISABLED_ICON: string = 'assets/icons/step-icon-green.png';
export const FLAG_BUTTON_TEXT: string = 'To flag';
export const FLAG_BUTTON_ICON: string = 'assets/icons/flag-icon-green.png'
export const GAME_BOARD_HEADER_TITLE: string = "MINEFIELD'S GAME";
export const LOST_MODAL_HEADER_TITLE: string = 'Lost Game';
export const LOST_MODAL_TEXT: string = 'So bad! Try another game. Good luck!';
export const LOST_MODAL_BUTTONS_1_TEXT: string = 'Ok';
export const WON_MODAL_HEADER_TITLE: string = "Congratulations!";
export const WON_MODAL_TEXT: string = "congratulations! Don't forget to check the ranked list, maybe you are the number 1!";
export const WON_MODAL_BUTTONS_1_TEXT: string = 'Ok';
export const FLAG_BUTTON_ENABLED_ICON: string = 'assets/icons/flag-icon.png';
export const FLAG_BUTTON_DISABLED_ICON: string = 'assets/icons/flag-icon-green.png';